# Generated by Django 4.2.27 on 2026-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('engine', models.CharField(max_length=200)),
                ('horsepower', models.PositiveIntegerField()),
                ('top_speed', models.PositiveIntegerField(help_text='Top speed in km/h')),
                ('acceleration', models.DecimalField(decimal_places=1, help_text='0-100 km/h time in seconds', max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, help_text='MSRP in USD', max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
