# Generated by Django 4.2.27 on 2026-01-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='car',
            name='wiki_page_id',
            field=models.PositiveIntegerField(blank=True, help_text='Autopedia wiki page ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='acceleration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='0-100 km/h time in seconds', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MSRP in USD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.PositiveIntegerField(blank=True, help_text='Top speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
