# Generated by Django 4.2.27 on 2026-01-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_wiki_and_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='data_source',
            field=models.CharField(default='manual', help_text='manual, wikipedia, autopedia', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='generation_code',
            field=models.CharField(blank=True, help_text='e.g., W210, Mk7, E39', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='generation_years',
            field=models.CharField(blank=True, help_text='e.g., 1995-2002', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='wikipedia_page_id',
            field=models.PositiveIntegerField(blank=True, help_text='Wikipedia page ID', null=True, unique=True),
        ),
    ]
