# Generated by Django 4.2.27 on 2026-01-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_body_style_car_data_source_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', 'name']},
        ),
        migrations.RemoveField(
            model_name='car',
            name='acceleration',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='generation_code',
        ),
        migrations.RemoveField(
            model_name='car',
            name='generation_years',
        ),
        migrations.RemoveField(
            model_name='car',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='top_speed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='wikipedia_page_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='car_class',
            field=models.CharField(blank=True, help_text='e.g., Mid-size luxury SUV', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='production_years',
            field=models.CharField(blank=True, help_text='e.g., 2000-present', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='data_source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='wiki_page_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='e.g., First Generation, Mk7', max_length=100)),
                ('code', models.CharField(blank=True, help_text='e.g., W210, E39', max_length=50)),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, help_text='Leave empty if still in production', null=True)),
                ('engine', models.CharField(blank=True, max_length=300)),
                ('horsepower', models.CharField(blank=True, help_text='e.g., 300 hp (224 kW)', max_length=100)),
                ('torque', models.CharField(blank=True, help_text='e.g., 270 lb⋅ft (366 N⋅m)', max_length=100)),
                ('top_speed', models.CharField(blank=True, help_text='e.g., 155 mph', max_length=100)),
                ('acceleration', models.CharField(blank=True, help_text='0-60 or 0-100 time', max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='cars.car')),
            ],
            options={
                'ordering': ['-year_start'],
            },
        ),
    ]
